# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Liquid Information From a Solidmoose
email: unknown
description: > # this means to ignore newlines until "baseurl:"
    This is a blog where I will discuss things that I believe are relevant to
    a reader's interests. If you're reading this, I hope I have provided a solution
    to your problem in one way or another. Lots of tech jabber will follow, including
    but not limited to things relevant to C++, Java, HTML, CSS, Webkit, and other tech jargon
    and acronyms.
baseurl: "" # the subpath of your site, e.g. /blog
url: "solidmoose.github.io" # the base hostname & protocol for your site
twitter_username: solidmoose
github_username:  solidmoose

# Build settings
markdown: kramdown
theme: minima
